name=FlashTimer
version=3.0.0
author=Nimb777
sentence=Detects single, double and long presses from a flash button.
paragraph=FlashTimer library that provides detection of single, double and long button presses.
category=Timing
url=https://github.com/Nimb777/FlashTimer
architectures=*